USE [master]
GO

/****** Object:  Database [UpstartTestDb]    Script Date: 2/26/2020 3:44:38 PM ******/
CREATE DATABASE [UpstartTestDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UpstartTestDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\UpstartTestDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UpstartTestDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\UpstartTestDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UpstartTestDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UpstartTestDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UpstartTestDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UpstartTestDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UpstartTestDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UpstartTestDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [UpstartTestDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UpstartTestDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UpstartTestDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UpstartTestDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UpstartTestDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UpstartTestDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UpstartTestDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UpstartTestDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UpstartTestDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UpstartTestDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UpstartTestDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UpstartTestDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UpstartTestDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UpstartTestDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UpstartTestDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UpstartTestDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UpstartTestDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UpstartTestDb] SET RECOVERY FULL 
GO

ALTER DATABASE [UpstartTestDb] SET  MULTI_USER 
GO

ALTER DATABASE [UpstartTestDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UpstartTestDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UpstartTestDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UpstartTestDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UpstartTestDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UpstartTestDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UpstartTestDb] SET  READ_WRITE 
GO

